# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e7acf5370e08441216e4920b98b0ecdeded20cad67071416aa144281f88dfc2e95cdb1e1fddf12dbcb671e5dc42754ea5d4b31558b8fa90683dea8aae600bd

test:
  secret_key_base: 0e2b893685b9136401bf0f21496cb88091c1856987992d7eecd3836448c8d602f2ece2f75429c01227525373e24f8ed7e7229c6093d95d99d50c9171cda4a7a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
